# Reference: http://www.appveyor.com/docs/appveyor-yml

environment:
  environment: qa
  
version: 1.0.{build}
branches:
  only:
    - master


# Operating system (build VM template)
os: Windows Server 2012

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input

# clone directory
# clone_folder: c:\projects\myproject

# enable service required for build/tests
services:
  - mssql2012sp1        # start SQL Server 2012 SP1 Express
  - iis                 # start IIS

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# scripts to run before build
before_build:
  #- rake dbCreate

# scripts to run after build
after_build:
  - rake createArtifact

# to run your custom scripts instead of automatic MSBuild
build_script:
  - rake build

# to run your custom scripts instead of automatic tests
# test_script:

test:
  assemblies:
    - build\*.Specs.dll

artifacts:
  - path: deploy\*.zip
    name: appZip

deploy:
  - provider: WebDeploy
    server: https://waws-prod-blu-017.publish.azurewebsites.windows.net:443/msdeploy.axd?site=starscream-starter
    website: starscream-starter
    username: $starscream-starter
    password: kHbwofpzBaifjtSc7RcpTRon84SPvSABEWPtnBrKWu6QkcwdCmMFWLefaF6o
    ntlm: false
    artifact: appZip
  
# scripts to run before deployment
before_deploy:
  - rake dbRebuild
# scripts to run after deployment
after_deploy:

# to run your custom scripts instead of provider deployments
deploy_script:

# on successful build
on_success:
  
# on build failure
on_failure:
  
notifications:
  - provider: Webhook
    url: http://appharborservicehookendpoint.apphb.com/build/appveyor/Starscream
